In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.datasets import load_digits
digits = load_digits()

In [3]:
df1 = pd.DataFrame(digits.data)
df2 = pd.DataFrame(digits.target)

In [4]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df1, df2, random_state=0, test_size =0.2)

# Linear Kernel

In [5]:
from sklearn import svm
linear_svc = svm.SVC(kernel='linear')
linear_svc.fit(x_train, y_train)

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [7]:
y_pred1 = linear_svc.predict(x_test)

In [9]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred1))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        27
          1       0.94      0.97      0.96        35
          2       0.97      1.00      0.99        36
          3       0.97      1.00      0.98        29
          4       0.97      1.00      0.98        30
          5       0.97      0.97      0.97        40
          6       1.00      0.98      0.99        44
          7       1.00      0.97      0.99        39
          8       0.97      0.95      0.96        39
          9       0.97      0.95      0.96        41

avg / total       0.98      0.98      0.98       360



In [10]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred1))

[[27  0  0  0  0  0  0  0  0  0]
 [ 0 34  0  0  0  0  0  0  1  0]
 [ 0  0 36  0  0  0  0  0  0  0]
 [ 0  0  0 29  0  0  0  0  0  0]
 [ 0  0  0  0 30  0  0  0  0  0]
 [ 0  0  0  0  0 39  0  0  0  1]
 [ 0  1  0  0  0  0 43  0  0  0]
 [ 0  0  0  0  1  0  0 38  0  0]
 [ 0  1  1  0  0  0  0  0 37  0]
 [ 0  0  0  1  0  1  0  0  0 39]]


# Polynomial Kernel 

In [11]:
from sklearn import svm
poly_svc = svm.SVC(kernel='poly')
poly_svc.fit(x_train, y_train)

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [12]:
y_pred2 = poly_svc.predict(x_test)

In [13]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred2))

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        27
          1       0.94      0.97      0.96        35
          2       1.00      1.00      1.00        36
          3       1.00      1.00      1.00        29
          4       1.00      1.00      1.00        30
          5       0.97      0.97      0.97        40
          6       1.00      0.98      0.99        44
          7       1.00      1.00      1.00        39
          8       0.97      0.97      0.97        39
          9       0.98      0.98      0.98        41

avg / total       0.99      0.99      0.99       360



In [14]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred2))

[[27  0  0  0  0  0  0  0  0  0]
 [ 0 34  0  0  0  0  0  0  1  0]
 [ 0  0 36  0  0  0  0  0  0  0]
 [ 0  0  0 29  0  0  0  0  0  0]
 [ 0  0  0  0 30  0  0  0  0  0]
 [ 0  0  0  0  0 39  0  0  0  1]
 [ 0  1  0  0  0  0 43  0  0  0]
 [ 0  0  0  0  0  0  0 39  0  0]
 [ 0  1  0  0  0  0  0  0 38  0]
 [ 0  0  0  0  0  1  0  0  0 40]]


# Gaussian Kernel

In [15]:
from sklearn import svm
gaussian_svc = svm.SVC(kernel='rbf')
gaussian_svc.fit(x_train, y_train)

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [16]:
y_pred3 = gaussian_svc.predict(x_test)

In [17]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred3))

             precision    recall  f1-score   support

          0       1.00      0.67      0.80        27
          1       1.00      0.17      0.29        35
          2       1.00      0.25      0.40        36
          3       0.11      1.00      0.19        29
          4       1.00      0.50      0.67        30
          5       1.00      0.15      0.26        40
          6       1.00      0.39      0.56        44
          7       1.00      0.23      0.38        39
          8       0.00      0.00      0.00        39
          9       1.00      0.20      0.33        41

avg / total       0.82      0.33      0.37       360



C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [18]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred3))

[[18  0  0  9  0  0  0  0  0  0]
 [ 0  6  0 29  0  0  0  0  0  0]
 [ 0  0  9 27  0  0  0  0  0  0]
 [ 0  0  0 29  0  0  0  0  0  0]
 [ 0  0  0 15 15  0  0  0  0  0]
 [ 0  0  0 34  0  6  0  0  0  0]
 [ 0  0  0 27  0  0 17  0  0  0]
 [ 0  0  0 30  0  0  0  9  0  0]
 [ 0  0  0 39  0  0  0  0  0  0]
 [ 0  0  0 33  0  0  0  0  0  8]]


# Sigmoid Kernel

In [19]:
from sklearn import svm
sigmoid_svc = svm.SVC(kernel='sigmoid')
sigmoid_svc.fit(x_train, y_train)

C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\sklearn\utils\validation.py:578: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='sigmoid',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [23]:
y_pred4 = sigmoid_svc.predict(x_test)

In [24]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred4))

             precision    recall  f1-score   support

          0       0.00      0.00      0.00        27
          1       0.00      0.00      0.00        35
          2       0.00      0.00      0.00        36
          3       0.08      1.00      0.15        29
          4       0.00      0.00      0.00        30
          5       0.00      0.00      0.00        40
          6       0.00      0.00      0.00        44
          7       0.00      0.00      0.00        39
          8       0.00      0.00      0.00        39
          9       0.00      0.00      0.00        41

avg / total       0.01      0.08      0.01       360



C:\Program Files (x86)\Microsoft Visual Studio\Shared\Anaconda3_64\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [26]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,y_pred4))

[[ 0  0  0 27  0  0  0  0  0  0]
 [ 0  0  0 35  0  0  0  0  0  0]
 [ 0  0  0 36  0  0  0  0  0  0]
 [ 0  0  0 29  0  0  0  0  0  0]
 [ 0  0  0 30  0  0  0  0  0  0]
 [ 0  0  0 40  0  0  0  0  0  0]
 [ 0  0  0 44  0  0  0  0  0  0]
 [ 0  0  0 39  0  0  0  0  0  0]
 [ 0  0  0 39  0  0  0  0  0  0]
 [ 0  0  0 41  0  0  0  0  0  0]]
